image: janrtr/docker-phpunit-php7:7.1-phpunit5
 
# Select what we should cache
cache:
  paths:
  - vendor/

services:
  - postgres:latest

variables:
  POSTGRES_DB: syp-lxc
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "test"
 
before_script:
  - composer install

php7.1:
  stage: test
  script:
    - phpunit --coverage-text