image: janrtr/docker-phpunit-php7:7.1-phpunit6
 
stages:
  - test
  - deploy

# Select what we should cache
cache:
  paths:
  - vendor/

services:
  - postgres:latest

variables:
  POSTGRES_DB: syp-lxc
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "test"
 
before_script:
  - composer install

test:php7.1:
  stage: test
  script:
    - phpunit --coverage-text

test:php7.0:
  stage: test
  image: janrtr/docker-phpunit-php7:7.0-phpunit6
  script:
    - phpunit --coverage-text

deploy:dev:
  image: ruby:2.1
  script:
    # Trigger deploy webhook with secret
    - curl "https://lxd-api.lleon.de/"

