image: epcallan/php7-testing-phpunit:7.1-phpunit5
 
# Select what we should cache
cache:
  paths:
  - vendor/
 
before_script:
  - composer install
 
# We test PHP7
test:php7.1:
  image: php:7
  script:
  - phpunit --coverage-text