image: epcallan/php7-testing-phpunit:7.1-phpunit5
 
# Select what we should cache
cache:
  paths:
  - vendor/
 
before_script:
  - composer install

in_docker:
  stage: test
  script:
    - phpunit --coverage-text