dist: trusty
sudo: required

language: php
php:
  - '7.1'
  - '7.2'

services:
  - postgresql
  - redis-server

before_install:
  - sudo apt update
  - sudo apt install libssh2-php
  - echo "extension = ssh2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo $CERT_CRT >> client.crt
  - echo echo $CERT_KEY >> client.key
  - phpenv config-rm xdebug.ini


install:
#  - sudo apt --yes install snapd
#  - sudo snap install lxd
  - composer install --no-interaction


before_script:
  - psql -c 'create database travis_lexic_test;' -U postgres
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
  
#script: phpdbg -qrr ./vendor/bin/simple-phpunit
script: SYMFONY_PHPUNIT_VERSION=7.0 ./vendor/bin/simple-phpunit --coverage-text

stages:
  - test
  - name: release
    if: branch = master
  - name: deploy
    if: branch = master

