dist: trusty
sudo: required

language: php
php:
  - '7.1'
  - '7.2'

services:
  - postgresql
  - redis-server

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get --yes install snapd
  - sudo snap install lxd
  - sudo apt-get install -y --force-yes php-ssh2 php-curl php-xml php-zip php-dom
  - composer install


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

stages:
  - test
  - name: release
    if: branch = master
  - name: deploy
    if: branch = master


jobs:
  include:
    - stage: test
      script: phpunit
    - stage: release
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true