version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/jan/Schreibtisch/Desktop/cert/client.crt:/srv/lexic/client.crt"
      - "/home/jan/Schreibtisch/Desktop/cert/client.key:/srv/lexic/client.key"
      - ".:/www/symfony"
  postgres:
    image: "postgres:9.6.7-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
  redis:
    image: "redis:alpine"
