version: '2'
services:
  web:
    image: "git.janrtr.de:4567/syp-lxc/backend"
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./client.crt:/srv/lexic/client.crt"
      - "./client.key:/srv/lexic/client.key"
      - "./:/www/symfony"
  postgres:
    image: "postgres:9.6.6-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
  redis:
    image: "redis:alpine"
