version: '2'
services:
  web:
    image: "lexicforlxd/web-backend"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${CLIENT_CERT_PATH}:/srv/lexic/client.crt"
      - "${CLIENT_KEY_PATH}:/srv/lexic/client.key"
      - "${SERVER_CERT_PATH}:/etc/nginx/server.crt"
      - "${SERVER_KEY_PATH}:/etc/nginx/server.key"
      - "${SSH_KEY_PATH}:/srv/lexic/ssh"
      - "${SSH_PUB_PATH}:/srv/lexic/ssh.pub"
  postgres:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"