version: '2'
services:
  web:
    image: "lexicforlxd/web-backend"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./cert.pem:/srv/lexic/client.crt"
      - "./key.pem:/srv/lexic/client.key"
      - "./ssh:/srv/lexic/ssh"
      - "./ssh.pub:/srv/lexic/ssh.pub"
      - "./:/www/symfony"
  postgres:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"