version: '2'
services:
  web:
    image: "lexicforlxd/web-backend"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/path/to/cert/client.crt:/srv/lexic/client.crt"
      - "/path/to/cert/client.key:/srv/lexic/client.key"
      - "/path/to/servercert/server.key:/etc/nginx/server.key"
      - "/path/to/servercert/server.key:/etc/nginx/server.key"
      - "/path/to/ssh/ssh:/srv/lexic/ssh"
      - "/path/to/ssh/ssh.pub:/srv/lexic/ssh.pub"
  postgres:
    image: "postgres:9.6.7-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"