version: '2'
services:
  web:
    image: "git.janrtr.de:4567/syp-lxc/backend"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/path/to/cert/client.crt:/srv/lexic/client.crt"
      - "/path/to/cert/client.key:/srv/lexic/client.key"
      - "/path/to/servercert/server.key:/etc/nginx/server.key"
      - "/path/to/servercert/server.key:/etc/nginx/server.key"
  postgres:
    image: "postgres:9.6.7-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
  redis:
    image: "redis:alpine"
