version: '3'
services:
  web:
    container_name: ${CONTAINER_WEB_NAME}
    image: lexicforlxd/web-backend:latest
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ${CLIENT_CERT_PATH}:/srv/lexic/client.crt
      - ${CLIENT_KEY_PATH}:/srv/lexic/client.key
      - ${SSH_KEY_PATH}:/srv/lexic/ssh
      - ${SSH_PUB_PATH}:/srv/lexic/ssh.pub
      - ./:/www/symfony
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}


  postgres:
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}


networks:
  default:
    external:
      name: ${NETWORK}