version: '3'
services:
  web:
    container_name: ${CONTAINER_WEB_NAME}
    image: lexicforlxd/web-backend:latest
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ${CLIENT_CERT_PATH}:/srv/lexic/client.crt
      - ${CLIENT_KEY_PATH}:/srv/lexic/client.key
      - ${SSH_KEY_PATH}:/srv/lexic/ssh
      - ${SSH_PUB_PATH}:/srv/lexic/ssh.pub
    environment:
      SECRET: ${SECRET}
      CONTAINER_DB_NAME: ${CONTAINER_DB_NAME}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      NAGIOS_USERNAME: ${NAGIOS_USERNAME}
      NAGIOS_PASSWORD: ${NAGIOS_PASSWORD}
      WEB_FRONTEND_DOMAIN: ${WEB_FRONTEND_DOMAIN}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}


  postgres:
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:10-alpine
    restart: unless-stopped
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
